# Generated by Django 3.1.1 on 2020-12-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_followers_likes_newposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='newposts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='newposts',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
