# Generated by Django 3.1.1 on 2020-12-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201214_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newposts',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
