# Generated by Django 3.1.1 on 2020-12-28 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20201222_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followers',
            name='follower',
        ),
        migrations.AddField(
            model_name='followers',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='following', to='network.user'),
            preserve_default=False,
        ),
    ]
